version: "3.9"

services:
  nginx:
    image: nginx:1.27.2
    container_name: nginx
    ports:
      - "3000:80"
    volumes:
      - ./nginx_conf:/etc/nginx/conf.d
      - static:/app/static
      - media:/app/media
      - ./media:/app/media
      - ./static:/app/static
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - backend
      - frontend
      - redis

  redis:
    image: redis:7.2-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./storage/redis:/data

  backend:
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - ./backend/app:/code/app
      - type: bind
        source: ./media/
        target: /media/
    tty: true
    command: fastapi run app/main.py --port 8000 --reload
  
  frontend:
    build:
      context: ./frontend
      dockerfile: ./dev.Dockerfile
    volumes:
      - ./frontend:/app
      - ./media/:/app/media/
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev