version: "3.9"

services:
  nginx:
    image: nginx:1.27.2
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx_conf/default.prod.conf:/etc/nginx/conf.d/default.conf
      - static:/app/static
      - media:/app/media
      - ./media:/app/media
      - ./static:/app/static
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - backend
      - frontend
      - redis

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  redis:
    image: redis:7.2-alpine
    restart: always
    volumes:
      - ./storage/redis:/data
    
  backend:
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: ./media/
        target: /media/
    tty: true
    command: fastapi run app/main.py --port 8000 --reload
  
  frontend:
    build:
      context: ./frontend
      dockerfile: prod.Dockerfile
    restart: always